FROM ubuntu:20.04

# squelches tzdata's install prompt
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y libboost-system \
    && apt-get install -y libboost-filesystem \
    && apt-get install -y libboost-thread \
    && apt-get install -y libboost-program-options \
    && apt-get install -y libboost-iostreams \
    && apt-get install -y libboost-regex \
    && apt-get install -y mariadb-client \
    && apt-get install -y libmariadbclient-dev \
    && apt-get install -y libreadline8 \
    && adduser -q -u 1000 trinitycore

COPY ./trinitycore /opt/trinitycore

ENV DEBIAN_FRONTEND=

CMD ["/bin/bash", "-c", "while true ;sleep 5; do continue; done"]
